openapi: 3.0.3
info:
  title: Goat facts Service
  description: Service for obtaining your daily dose of goat facts
  version: "1.0"
servers:
- url: http://localhost:8080
- url: https://goatops.farm
paths:
  /:
    get:
      tags:
      - goatfacts
      summary: Index goatfacts
      operationId: goatfacts#Index
      responses:
        "200":
          description: OK response.
          content:
            text/html:
              schema:
                type: string
                example:
                - 69
                - 115
                - 115
                - 101
                - 32
                - 100
                - 111
                - 108
                - 111
                - 114
                - 32
                - 100
                - 111
                - 108
                - 111
                - 114
                - 101
                - 32
                - 101
                - 115
                - 115
                - 101
                - 46
                format: binary
              example:
              - 69
              - 116
              - 32
              - 97
              - 117
              - 116
              - 32
              - 110
              - 101
              - 99
              - 101
              - 115
              - 115
              - 105
              - 116
              - 97
              - 116
              - 105
              - 98
              - 117
              - 115
              - 46
  /api/facts:
    get:
      tags:
      - goatfacts
      summary: ListFacts goatfacts
      operationId: goatfacts#ListFacts
      responses:
        "200":
          description: OK response.
          content:
            application/json:
              schema:
                type: array
                items:
                  type: string
                  example: Beatae recusandae.
                example:
                - Modi sint saepe.
                - Quae est ullam velit quasi.
              example:
              - Rerum recusandae blanditiis ex.
              - Itaque ullam voluptatem sit molestias.
  /api/facts/random:
    get:
      tags:
      - goatfacts
      summary: RandomFacts goatfacts
      operationId: goatfacts#RandomFacts
      parameters:
      - name: "n"
        in: query
        description: Number of random facts
        allowEmptyValue: true
        schema:
          type: integer
          description: Number of random facts
          example: 9059312564685485055
          format: int64
        example: 6983850233654289973
      responses:
        "200":
          description: OK response.
          content:
            application/json:
              schema:
                type: array
                items:
                  type: string
                  example: Perspiciatis rem ad repellat consequatur culpa.
                example:
                - Perspiciatis beatae fugiat nesciunt explicabo.
                - Cum voluptas est alias aut eius.
              example:
              - Ea non rerum aut esse quia mollitia.
              - Fugiat temporibus vero expedita.
        "400":
          description: Bad Request response.
          content:
            application/vnd.goa.error:
              schema:
                $ref: '#/components/schemas/Error'
              example:
                id: 3F1FKVRR
                message: Value of ID must be an integer
                name: bad_request
  /api/openapi.json:
    get:
      tags:
      - goatfacts
      summary: Download ./gen/http/openapi3.json
      operationId: goatfacts#/api/openapi.json
      responses:
        "200":
          description: File downloaded
components:
  schemas:
    Error:
      type: object
      properties:
        fault:
          type: boolean
          description: Is the error a server-side fault?
          example: true
        id:
          type: string
          description: ID is a unique identifier for this particular occurrence of
            the problem.
          example: 123abc
        message:
          type: string
          description: Message is a human-readable explanation specific to this occurrence
            of the problem.
          example: parameter 'p' must be an integer
        name:
          type: string
          description: Name is the name of this class of errors.
          example: bad_request
        temporary:
          type: boolean
          description: Is the error temporary?
          example: false
        timeout:
          type: boolean
          description: Is the error a timeout?
          example: false
      example:
        id: 3F1FKVRR
        message: Value of ID must be an integer
        name: bad_request
      required:
      - name
      - id
      - message
      - temporary
      - timeout
      - fault
tags:
- name: goatfacts
  description: The goatfacts service provides you with important facts about goats.
