openapi: 3.0.3
info:
  title: Goat facts Service
  description: Service for obtaining your daily dose of goat facts
  version: "1.0"
servers:
- url: http://localhost:8080
- url: https://goatops.farm
paths:
  /:
    get:
      tags:
      - goatfacts
      summary: Index goatfacts
      operationId: goatfacts#Index
      responses:
        "200":
          description: OK response.
          content:
            text/html:
              schema:
                type: string
                example:
                - 65
                - 117
                - 116
                - 32
                - 101
                - 105
                - 117
                - 115
                - 32
                - 100
                - 111
                - 108
                - 111
                - 114
                - 101
                - 115
                - 32
                - 112
                - 101
                - 114
                - 115
                - 112
                - 105
                - 99
                - 105
                - 97
                - 116
                - 105
                - 115
                - 32
                - 97
                - 98
                - 46
                format: binary
              example:
              - 69
              - 116
              - 32
              - 97
              - 117
              - 116
              - 32
              - 110
              - 101
              - 99
              - 101
              - 115
              - 115
              - 105
              - 116
              - 97
              - 116
              - 105
              - 98
              - 117
              - 115
              - 46
  /api/openapi.json:
    get:
      tags:
      - goatfacts
      summary: Download ./gen/http/openapi3.json
      operationId: goatfacts#/api/openapi.json
      responses:
        "200":
          description: File downloaded
  /api/swagger/{*path}:
    get:
      tags:
      - goatfacts
      summary: Download ./static/swagger
      operationId: goatfacts#/api/swagger/{*path}
      parameters:
      - name: path
        in: path
        description: Relative file path
        required: true
      responses:
        "200":
          description: File not found
        "404":
          description: File not found
  /api/v1/facts:
    get:
      tags:
      - goatfacts
      summary: ListFacts goatfacts
      operationId: goatfacts#ListFacts
      responses:
        "200":
          description: OK response.
          content:
            application/json:
              schema:
                type: array
                items:
                  type: string
                  example: Recusandae vel dolorum.
                example:
                - Saepe ipsum quae est.
                - Velit quasi quaerat perspiciatis.
                - Ad repellat.
              example:
              - Dolor dolore esse temporibus error rerum.
              - Blanditiis ex alias.
  /api/v1/facts/random:
    get:
      tags:
      - goatfacts
      summary: RandomFacts goatfacts
      operationId: goatfacts#RandomFacts
      parameters:
      - name: "n"
        in: query
        description: Number of random facts
        allowEmptyValue: true
        schema:
          type: integer
          description: Number of random facts
          example: 8103290738173953045
          format: int64
        example: 8035204789576502952
      responses:
        "200":
          description: OK response.
          content:
            application/json:
              schema:
                type: array
                items:
                  type: string
                  example: Culpa veniam.
                example:
                - Beatae fugiat.
                - Explicabo nihil.
              example:
              - Molestias voluptate id.
              - Inventore ea.
              - Rerum aut esse quia mollitia.
              - Fugiat temporibus vero expedita.
        "400":
          description: Bad Request response.
          content:
            application/vnd.goa.error:
              schema:
                $ref: '#/components/schemas/Error'
              example:
                id: 3F1FKVRR
                message: Value of ID must be an integer
                name: bad_request
components:
  schemas:
    Error:
      type: object
      properties:
        fault:
          type: boolean
          description: Is the error a server-side fault?
          example: true
        id:
          type: string
          description: ID is a unique identifier for this particular occurrence of
            the problem.
          example: 123abc
        message:
          type: string
          description: Message is a human-readable explanation specific to this occurrence
            of the problem.
          example: parameter 'p' must be an integer
        name:
          type: string
          description: Name is the name of this class of errors.
          example: bad_request
        temporary:
          type: boolean
          description: Is the error temporary?
          example: false
        timeout:
          type: boolean
          description: Is the error a timeout?
          example: false
      example:
        id: 3F1FKVRR
        message: Value of ID must be an integer
        name: bad_request
      required:
      - name
      - id
      - message
      - temporary
      - timeout
      - fault
tags:
- name: goatfacts
  description: The goatfacts service provides you with important facts about goats.
